var annotated_dup =
[
    [ "BF_type", "structBF__type.html", null ],
    [ "BM_type", "structBM__type.html", null ],
    [ "bmc_buffer_type", "structbmc__buffer__type.html", null ],
    [ "C_data", "structC__data.html", null ],
    [ "D_data", "structD__data.html", null ],
    [ "EB_data", "structEB__data.html", null ],
    [ "EM_data1", "structEM__data1.html", null ],
    [ "EM_data2", "structEM__data2.html", null ],
    [ "EM_serial", "structEM__serial.html", null ],
    [ "EM_version", "structEM__version.html", null ],
    [ "ha_daq_calib_type", "structha__daq__calib__type.html", null ],
    [ "M_data", "structM__data.html", null ],
    [ "M_time_data", "structM__time__data.html", null ],
    [ "MREG", "unionMREG.html", null ],
    [ "MREG32", "unionMREG32.html", null ],
    [ "MREG64", "unionMREG64.html", null ],
    [ "mx_log_packed_t", "structmx__log__packed__t.html", null ],
    [ "mx_logpage_t", "structmx__logpage__t.html", null ],
    [ "mx_status_packed_t", "structmx__status__packed__t.html", null ],
    [ "PWMDC", "unionPWMDC.html", null ],
    [ "ringBufS_t", "structringBufS__t.html", null ],
    [ "serial_buffer_type_ss", "structserial__buffer__type__ss.html", null ],
    [ "spi1_configuration_t", "structspi1__configuration__t.html", null ],
    [ "spi2_configuration_t", "structspi2__configuration__t.html", null ],
    [ "spi_link_type", "structspi__link__type.html", null ],
    [ "spi_link_type_ss", "structspi__link__type__ss.html", null ],
    [ "spi_stat_type_ss", "structspi__stat__type__ss.html", null ],
    [ "terminal_type", "structterminal__type.html", null ],
    [ "uart1_status_t", "unionuart1__status__t.html", null ],
    [ "uart2_status_t", "unionuart2__status__t.html", null ],
    [ "uart3_status_t", "unionuart3__status__t.html", null ],
    [ "V_data", "structV__data.html", null ],
    [ "V_help", "structV__help.html", null ],
    [ "VM_type", "structVM__type.html", null ]
];